import datetime as dt
date=dt.datetime.now()

f = open("./igzo_tcam_100by4.cir",'w')
totalwaynumber=1
totalcellnumber=1
f.write("* Title : 1Cell IGZO\n* Date :"+str(date.year)+"-"+str(date.month)+"-"+str(date.day)+"\n* Author : SEO\n* Editor = Byun \n\n***** MOS Level=1 *****\n.model nigzo nmos level=61 vt0=0 vfb=-0.5 delta=0.4 gmin=6e23 vmin=0.05 sigma0=-1e-18 IOL=0 epsi=3.9 tox=1e-8 alphasat=0.7 gamma=0.06\n.model ncmos NMOS level=1 vto=0\n.model pcmos pmos level=1 vto=0\n\n*##### Netlist #####\n")
for j in range(0,totalwaynumber):
    for i in range(0,totalcellnumber):
        f.write("m1waynumber%.1dcellnumber%.4d n2waynumber%.1dcellnumber%.4d n1waynumber%.1dcellnumber%.4d n3waynumber%.1dcellnumber%.4d nigzo L=1u W=1u\nm2waynumber%.1dcellnumber%.4d nmlwaynumber%.1d n3waynumber%.1dcellnumber%.4d n7waynumber%.1dcellnumber%.4d nigzo L=1u W=1u\nm3waynumber%.1dcellnumber%.4d n7waynumber%.1dcellnumber%.4d nslwaynumber%.1dcellnumber%.4d vss nigzo L=1u W=1u\nm1bwaynumber%.1dcellnumber%.4d n5waynumber%.1dcellnumber%.4d n4waynumber%.1dcellnumber%.4d n6waynumber%.1dcellnumber%.4d nigzo L=1u W=1u\nm2bwaynumber%.1dcellnumber%.4d nmlwaynumber%.1d n6waynumber%.1dcellnumber%.4d n8waynumber%.1dcellnumber%.4d nigzo L=1u W=1u\nm3bwaynumber%.1dcellnumber%.4d n8waynumber%.1dcellnumber%.4d nslbwaynumber%.1dcellnumber%.4d vss nigzo L=1u W=1u\n"%(j,i,j,i,j,i,j,i,j,i,j,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,j,i,j,i,j,i,j,i,j,i))
    f.write("mmlwaynumber%.1dcharge nmlwaynumber%.1d nmlwaynumber%.1dcharge vdd2 ncmos L=1u W=1u\nmmlwaynumber%.1dsablbcharge nmlwaynumber%.1dsablb nmlwaynumber%.1dsablbcharge vdd2 ncmos L=1u W=1u\n"%(j,j,j,j,j,j))
    for i in range(0,totalcellnumber):
        f.write("mslchargewaynumber%.1dcellnumber%.4d nslwaynumber%.1dcellnumber%.4d nslchargewaynumber%.1dcellnumber%.4d vdd ncmos L=1u W=1u\nmslbchargewaynumber%.1dcellnumber%.4d nslbwaynumber%.1dcellnumber%.4d nslbchargewaynumber%.1dcellnumber%.4d vdd ncmos L=1u W=1u\nmsldischargewaynumber%.1dcellnumber%.4d nslwaynumber%.1dcellnumber%.4d nsldischargewaynumber%.1dcellnumber%.4d vss ncmos L=1u W=1u\nmslbdischargewaynumber%.1dcellnumber%.4d nslbwaynumber%.1dcellnumber%.4d nslbdischargewaynumber%.1dcellnumber%.4d vss ncmos L=1u W=1u\nmsan1waynumber%.1dcellnumber%.4d nsablwaynumber%.1dcellnumber%.4d nsablbwaynumber%.1dcellnumber%.4d nsasanwaynumber%.1dcellnumber%.4d ncmos L=1u W=1u\nmsan2waynumber%.1dcellnumber%.4d nsablbwaynumber%.1dcellnumber%.4d nsablwaynumber%.1dcellnumber%.4d nsasanwaynumber%.1dcellnumber%.4d ncmos L=1u W=1u\nmsap1waynumber%.1dcellnumber%.4d nsasapwaynumber%.1dcellnumber%.4d nsablbwaynumber%.1dcellnumber%.4d nsablwaynumber%.1dcellnumber%.4d pcmos L=1u W=2.8u\nmsap2waynumber%.1dcellnumber%.4d nsasapwaynumber%.1dcellnumber%.4d nsablwaynumber%.1dcellnumber%.4d nsablbwaynumber%.1dcellnumber%.4d pcmos L=1u W=2.8u\nmsabn1waynumber%.1dcellnumber%.4d nsabblwaynumber%.1dcellnumber%.4d nsabblbwaynumber%.1dcellnumber%.4d nsabsanwaynumber%.1dcellnumber%.4d ncmos L=1u W=1u\nmsabn2waynumber%.1dcellnumber%.4d nsabblbwaynumber%.1dcellnumber%.4d nsabblwaynumber%.1dcellnumber%.4d nsabsanwaynumber%.1dcellnumber%.4d ncmos L=1u W=1u\nmsabp1waynumber%.1dcellnumber%.4d nsabsapwaynumber%.1dcellnumber%.4d nsabblbwaynumber%.1dcellnumber%.4d nsabblwaynumber%.1dcellnumber%.4d pcmos L=1u W=2.8u\nmsabp2waynumber%.1dcellnumber%.4d nsabsapwaynumber%.1dcellnumber%.4d nsabblwaynumber%.1dcellnumber%.4d nsabblbwaynumber%.1dcellnumber%.4d pcmos L=1u W=2.8u\n"%(j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i))
    f.write("mmlwaynumber%.1dsan1 nmlwaynumber%.1dsabl nmlwaynumber%.1dsablb nmlwaynumber%.1dsasan ncmos L=1u W=1u\nmmlwaynumber%.1dsan2 nmlwaynumber%.1dsablb nmlwaynumber%.1dsabl nmlwaynumber%.1dsasan ncmos L=1u W=1u\nmmlwaynumber%.1dsap1 nmlwaynumber%.1dsasap nmlwaynumber%.1dsablb nmlwaynumber%.1dsabl pcmos L=1u W=2.8u\nmmlwaynumber%.1dsap2 nmlwaynumber%.1dsasap nmlwaynumber%.1dsabl nmlwaynumber%.1dsablb pcmos L=1u W=2.8u\n"%(j,j,j,j,j,j,j,j,j,j,j,j,j,j,j,j))
    for i in range(0,totalcellnumber):
        f.write("mcslwaynumber%.1dcellnumber%.4d nsablwaynumber%.1dcellnumber%.4d ncslwaynumber%.1dcellnumber%.4d noutputwaynumber%.1dcellnumber%.4d ncmos L=1u W=1u\nmcslbwaynumber%.1dcellnumber%.4d nsablbwaynumber%.1dcellnumber%.4d ncslwaynumber%.1dcellnumber%.4d noutputbwaynumber%.1dcellnumber%.4d ncmos L=1u W=1u\nmwewaynumber%.1dcellnumber%.4d ninputwaynumber%.1dcellnumber%.4d nwewaynumber%.1dcellnumber%.4d noutputwaynumber%.1dcellnumber%.4d ncmos L=1u W=1u\nmwebwaynumber%.1dcellnumber%.4d ninputbwaynumber%.1dcellnumber%.4d nwewaynumber%.1dcellnumber%.4d noutputbwaynumber%.1dcellnumber%.4d ncmos L=1u W=1u\n\nc1waynumber%.1dcellnumber%.4d n3waynumber%.1dcellnumber%.4d vss C=1n IC=1.5\nc2waynumber%.1dcellnumber%.4d n6waynumber%.1dcellnumber%.4d vss C=1n IC=0\ncslwaynumber%.1dcellnumber%.4d nslwaynumber%.1dcellnumber%.4d vss C=100p IC=0\ncslbwaynumber%.1dcellnumber%.4d nslbwaynumber%.1dcellnumber%.4d vss C=100p IC=0\ncsablwaynumber%.1dcellnumber%.4d nsablwaynumber%.1dcellnumber%.4d vss C=100p IC=0\ncsablbwaynumber%.1dcellnumber%.4d nsablbwaynumber%.1dcellnumber%.4d vss C=100p IC=0\ncsabblwaynumber%.1dcellnumber%.4d nsabblwaynumber%.1dcellnumber%.4d vss C=100p IC=0\ncsabblbwaynumber%.1dcellnumber%.4d nsabblbwaynumber%.1dcellnumber%.4d vss C=100p IC=0\n"%(j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i))
    f.write("cmlwaynumber%.1dsabl nmlwaynumber%.1dsabl vss C=100p IC=0\ncmlwaynumber%.1dsablb nmlwaynumber%.1dsablb vss C=100p IC=0\n\n\n*##### POWER #####\n"%(j,j,j,j))
    for i in range(0,totalcellnumber):
        f.write("vsasanwaynumber%.1dcellnumber%.4d nsasanwaynumber%.1dcellnumber%.4d vss pwl 0 0 100u 0\nvsasapwaynumber%.1dcellnumber%.4d nsasapwaynumber%.1dcellnumber%.4d vss pwl 0 0 100u 0\nvsabsanwaynumber%.1dcellnumber%.4d nsabsanwaynumber%.1dcellnumber%.4d vss pwl 0 0 100u 0\nvsabsapwaynumber%.1dcellnumber%.4d nsabsapwaynumber%.1dcellnumber%.4d vss pwl 0 0 100u 0\n"%(j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i))
    f.write("vmlwaynumber%.1dsasan nmlwaynumber%.1dsasan vss pwl 0 0 90u 0 91u -1.5 100u -1.5\nvmlwaynumber%.1dsasap nmlwaynumber%.1dsasap vss pwl 0 0 90u 0 91u 1.5 100u 1.5\n"%(j,j,j,j))
    for i in range(0,totalcellnumber):
        f.write("v1waynumber%.1dcellnumber%.4d n1waynumber%.1dcellnumber%.4d nwlwaynumber%.1dcellnumber%.4d 0\nv2waynumber%.1dcellnumber%.4d n2waynumber%.1dcellnumber%.4d nsablwaynumber%.1dcellnumber%.4d 0\nv4waynumber%.1dcellnumber%.4d n4waynumber%.1dcellnumber%.4d nwlbwaynumber%.1dcellnumber%.4d 0\nv5waynumber%.1dcellnumber%.4d n5waynumber%.1dcellnumber%.4d nsabblwaynumber%.1dcellnumber%.4d 0\n"%(j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i))
    f.write("vmlwaynumber%.1d nmlwaynumber%.1d nmlwaynumber%.1dsabl 0\n"%(j,j,j))  # switch
    for i in range(0,totalcellnumber):
        f.write("vwlwaynumber%.1dcellnumber%.4d nwlwaynumber%.1dcellnumber%.4d vss pwl 0 0 100u 0\nvwlbwaynumber%.1dcellnumber%.4d nwlbwaynumber%.1dcellnumber%.4d vss pwl 0 0 100u 0\nvslchargewaynumber%.1dcellnumber%.4d nslchargewaynumber%.1dcellnumber%.4d vss pwl 0 0 5u 0 6u 3 7u 3 8u 0 100u 0\nvsldischargewaynumber%.1dcellnumber%.4d nsldischargewaynumber%.1dcellnumber%.4d vss pwl 0 0 1u 0 2u 3 3u 3 4u 0 100u 0\nvslbchargewaynumber%.1dcellnumber%.4d nslbchargewaynumber%.1dcellnumber%.4d vss pwl 0 0 100u 0\nvslbdischargewaynumber%.1dcellnumber%.4d nslbdischargewaynumber%.1dcellnumber%.4d vss pwl 0 0 1u 0 2u 3 3u 3 4u 0 100u 0\n"%(j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i))
    f.write("vmlwaynumber%.1dcharge nmlwaynumber%.1dcharge vss pwl 0 0 1u 0 2u 3 19u 3 20u 0 100u 0\nvmlwaynumber%.1dsablbcharge nmlwaynumber%.1dsablbcharge vss pwl 0 0 1u 0 2u 3 19u 3 20u 0 100u 0\n"%(j,j,j,j))
    for i in range(0,totalcellnumber):
        f.write("vcslwaynumber%.1dcellnumber%.4d ncslwaynumber%.1dcellnumber%.4d vss pwl 0 0 100u 0\nvwewaynumber%.1dcellnumber%.4d nwewaynumber%.1dcellnumber%.4d vss pwl 0 0 100u 0\nvsablchargewaynumber%.1dcellnumber%.4d nsablchargewaynumber%.1dcellnumber%.4d vss pwl 0 0 1u 0 2u 3 12u 3 13u 0 100u 0\nvsablbchargewaynumber%.1dcellnumber%.4d nsablbchargewaynumber%.1dcellnumber%.4d vss pwl 0 0 1u 0 2u 3 12u 3 13u 0 100u 0\nvinputwaynumber%.1dcellnumber%.4d ninputwaynumber%.1dcellnumber%.4d vss 0\nvinputbwaynumber%.1dcellnumber%.4d ninputbwaynumber%.1dcellnumber%.4d vss 0\n"%(j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i,j,i))
    f.write("vdd vdd vss 3\nvdd2 vdd2 vss 3\nvss vss 0 0\n\n*##### INPUT & ANALYSIS #####\n\n.tran 1p 100u\n\n*##### OPTION #####\n.option scale=1u\n.option post node list acct dccap\n.op\n\n*##### OUTPUT #####\n\n.end")

f.close()
